import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

async function main() {
    const mongoose = (await import('mongoose')).default;
    const { connectDB } = await import('../lib/mongodb');
    const Problem = (await import('../models/Problem')).default;
    const { CSHARP_JSON_HELPERS, RUST_JSON_HELPERS } = await import('../lib/newLangCodegen');

    await connectDB();

    // ============== Print in Order (Foo) ==============
    {
        const p = await Problem.findOne({ title: 'Print in Order' });
        const starterCode: any = p!.starterCode.toObject ? p!.starterCode.toObject() : p!.starterCode;
        starterCode.go = `type Foo struct {\n}\n\nfunc NewFoo() *Foo {\n\treturn &Foo{}\n}\n\nfunc (f *Foo) First(printFirst func()) {\n\t// printFirst() outputs "first". Do not change or remove this line.\n\tprintFirst()\n}\n\nfunc (f *Foo) Second(printSecond func()) {\n\t// printSecond() outputs "second". Do not change or remove this line.\n\tprintSecond()\n}\n\nfunc (f *Foo) Third(printThird func()) {\n\t// printThird() outputs "third". Do not change or remove this line.\n\tprintThird()\n}`;
        starterCode.csharp = `class Foo {\n    public Foo() {\n    }\n\n    public void First(Action printFirst) {\n        // printFirst() outputs "first". Do not change or remove this line.\n        printFirst();\n    }\n\n    public void Second(Action printSecond) {\n        // printSecond() outputs "second". Do not change or remove this line.\n        printSecond();\n    }\n\n    public void Third(Action printThird) {\n        // printThird() outputs "third". Do not change or remove this line.\n        printThird();\n    }\n}`;
        starterCode.rust = `pub struct Foo {\n}\n\nimpl Foo {\n    pub fn new() -> Self {\n        Foo {}\n    }\n\n    pub fn first<F: Fn()>(&self, print_first: F) {\n        // print_first() outputs "first". Do not change or remove this line.\n        print_first();\n    }\n\n    pub fn second<F: Fn()>(&self, print_second: F) {\n        // print_second() outputs "second". Do not change or remove this line.\n        print_second();\n    }\n\n    pub fn third<F: Fn()>(&self, print_third: F) {\n        // print_third() outputs "third". Do not change or remove this line.\n        print_third();\n    }\n}`;
        starterCode.typescript = `class Foo {\n    constructor() {\n    }\n\n    first(printFirst: () => void): void {\n        // printFirst() outputs "first". Do not change or remove this line.\n        printFirst();\n    }\n\n    second(printSecond: () => void): void {\n        // printSecond() outputs "second". Do not change or remove this line.\n        printSecond();\n    }\n\n    third(printThird: () => void): void {\n        // printThird() outputs "third". Do not change or remove this line.\n        printThird();\n    }\n}`;
        p!.starterCode = starterCode;

        const cd: any = p!.customDriver.toObject ? p!.customDriver.toObject() : p!.customDriver;
        cd.go = `package main\n\nimport (\n\t"encoding/json"\n\t"fmt"\n\t"sync"\n)\n\nvar __output []string\nvar __mu sync.Mutex\n\n{{SOLUTION}}\n\nfunc main() {\n\tfoo := NewFoo()\n\tvar wg sync.WaitGroup\n\twg.Add(3)\n\tgo func() { defer wg.Done(); foo.Third(func() { __mu.Lock(); __output = append(__output, "third"); __mu.Unlock() }) }()\n\tgo func() { defer wg.Done(); foo.Second(func() { __mu.Lock(); __output = append(__output, "second"); __mu.Unlock() }) }()\n\tgo func() { defer wg.Done(); foo.First(func() { __mu.Lock(); __output = append(__output, "first"); __mu.Unlock() }) }()\n\twg.Wait()\n\tjoined := ""\n\tfor _, s := range __output { joined += s }\n\tout, _ := json.Marshal(joined)\n\tfmt.Println(string(out))\n}`;
        cd.csharp = `using System;\nusing System.Threading;\nusing System.Collections.Generic;\nusing System.Text;\n${CSHARP_JSON_HELPERS}\n{{SOLUTION}}\n\nclass Program {\n    static List<string> __output = new List<string>();\n    static object __lock = new object();\n\n    static void Main() {\n        var foo = new Foo();\n        var t3 = new Thread(() => foo.Third(() => { lock(__lock) { __output.Add("third"); } }));\n        var t2 = new Thread(() => foo.Second(() => { lock(__lock) { __output.Add("second"); } }));\n        var t1 = new Thread(() => foo.First(() => { lock(__lock) { __output.Add("first"); } }));\n        t3.Start(); t2.Start(); t1.Start();\n        t1.Join(); t2.Join(); t3.Join();\n        var sb = new StringBuilder();\n        foreach (var s in __output) sb.Append(s);\n        Console.WriteLine(Json.Stringify(sb.ToString()));\n    }\n}`;
        cd.rust = `fn main() {\n    let foo = std::sync::Arc::new(Foo::new());\n    let output: std::sync::Arc<std::sync::Mutex<Vec<String>>> = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));\n\n    let f3 = std::sync::Arc::clone(&foo); let o3 = std::sync::Arc::clone(&output);\n    let t3 = std::thread::spawn(move || { f3.third(|| { o3.lock().unwrap().push("third".to_string()); }); });\n    let f2 = std::sync::Arc::clone(&foo); let o2 = std::sync::Arc::clone(&output);\n    let t2 = std::thread::spawn(move || { f2.second(|| { o2.lock().unwrap().push("second".to_string()); }); });\n    let f1 = std::sync::Arc::clone(&foo); let o1 = std::sync::Arc::clone(&output);\n    let t1 = std::thread::spawn(move || { f1.first(|| { o1.lock().unwrap().push("first".to_string()); }); });\n\n    t3.join().unwrap(); t2.join().unwrap(); t1.join().unwrap();\n\n    let joined: String = output.lock().unwrap().join("");\n    println!("\\"{}\\"", joined);\n}`;
        cd.typescript = `const __output: string[] = [];\nconst foo = new Foo();\nconst p1 = new Promise<void>(r => setTimeout(() => { Promise.resolve(foo.third(() => { __output.push('third'); })).then(() => r()); }, 0));\nconst p2 = new Promise<void>(r => setTimeout(() => { Promise.resolve(foo.second(() => { __output.push('second'); })).then(() => r()); }, 0));\nconst p3 = new Promise<void>(r => setTimeout(() => { Promise.resolve(foo.first(() => { __output.push('first'); })).then(() => r()); }, 0));\nPromise.all([p1, p2, p3]).then(() => console.log(JSON.stringify(__output.join(''))));`;
        p!.customDriver = cd;
        await p!.save();
        console.log('Saved: Print in Order');
    }

    // ============== Print FooBar Alternately ==============
    {
        const p = await Problem.findOne({ title: 'Print FooBar Alternately' });
        const starterCode: any = p!.starterCode.toObject ? p!.starterCode.toObject() : p!.starterCode;
        starterCode.go = `type FooBar struct {\n\tn int\n}\n\nfunc NewFooBar(n int) *FooBar {\n\treturn &FooBar{n: n}\n}\n\nfunc (fb *FooBar) Foo(printFoo func()) {\n\tfor i := 0; i < fb.n; i++ {\n\t\t// Write your solution here\n\t\tprintFoo()\n\t}\n}\n\nfunc (fb *FooBar) Bar(printBar func()) {\n\tfor i := 0; i < fb.n; i++ {\n\t\t// Write your solution here\n\t\tprintBar()\n\t}\n}`;
        starterCode.csharp = `class FooBar {\n    private int n;\n\n    public FooBar(int n) {\n        this.n = n;\n    }\n\n    public void Foo(Action printFoo) {\n        for (int i = 0; i < n; i++) {\n            // Write your solution here\n            printFoo();\n        }\n    }\n\n    public void Bar(Action printBar) {\n        for (int i = 0; i < n; i++) {\n            // Write your solution here\n            printBar();\n        }\n    }\n}`;
        starterCode.rust = `pub struct FooBar {\n    n: i32,\n}\n\nimpl FooBar {\n    pub fn new(n: i32) -> Self {\n        FooBar { n }\n    }\n\n    pub fn foo<F: Fn()>(&self, print_foo: F) {\n        for _ in 0..self.n {\n            // Write your solution here\n            print_foo();\n        }\n    }\n\n    pub fn bar<F: Fn()>(&self, print_bar: F) {\n        for _ in 0..self.n {\n            // Write your solution here\n            print_bar();\n        }\n    }\n}`;
        starterCode.typescript = `class FooBar {\n    n: number;\n    constructor(n: number) {\n        this.n = n;\n    }\n\n    foo(printFoo: () => void): void {\n        for (let i = 0; i < this.n; i++) {\n            // Write your solution here\n            printFoo();\n        }\n    }\n\n    bar(printBar: () => void): void {\n        for (let i = 0; i < this.n; i++) {\n            // Write your solution here\n            printBar();\n        }\n    }\n}`;
        p!.starterCode = starterCode;

        const cd: any = p!.customDriver.toObject ? p!.customDriver.toObject() : p!.customDriver;
        cd.go = `package main\n\nimport (\n\t"encoding/json"\n\t"fmt"\n\t"io"\n\t"os"\n\t"sync"\n)\n\nvar __output []string\nvar __mu sync.Mutex\n\n{{SOLUTION}}\n\nfunc main() {\n\tinputBytes, _ := io.ReadAll(os.Stdin)\n\tvar raw map[string]interface{}\n\tjson.Unmarshal(inputBytes, &raw)\n\tn := int(raw["n"].(float64))\n\n\tfb := NewFooBar(n)\n\tvar wg sync.WaitGroup\n\twg.Add(2)\n\tgo func() { defer wg.Done(); fb.Bar(func() { __mu.Lock(); __output = append(__output, "bar"); __mu.Unlock() }) }()\n\tgo func() { defer wg.Done(); fb.Foo(func() { __mu.Lock(); __output = append(__output, "foo"); __mu.Unlock() }) }()\n\twg.Wait()\n\n\tjoined := ""\n\tfor _, s := range __output { joined += s }\n\tout, _ := json.Marshal(joined)\n\tfmt.Println(string(out))\n}`;
        cd.csharp = `using System;\nusing System.Threading;\nusing System.Collections.Generic;\nusing System.Text;\n${CSHARP_JSON_HELPERS}\n{{SOLUTION}}\n\nclass Program {\n    static List<string> __output = new List<string>();\n    static object __lock = new object();\n\n    static void Main() {\n        string input = Console.In.ReadToEnd();\n        var data = (Dictionary<string, object>)Json.Parse(input);\n        int n = Convert.ToInt32(data["n"]);\n\n        var fb = new FooBar(n);\n        var t2 = new Thread(() => fb.Bar(() => { lock(__lock) { __output.Add("bar"); } }));\n        var t1 = new Thread(() => fb.Foo(() => { lock(__lock) { __output.Add("foo"); } }));\n        t2.Start(); t1.Start();\n        t1.Join(); t2.Join();\n\n        var sb = new StringBuilder();\n        foreach (var s in __output) sb.Append(s);\n        Console.WriteLine(Json.Stringify(sb.ToString()));\n    }\n}`;
        cd.rust = `${RUST_JSON_HELPERS}\nuse std::io::Read;\n\nfn main() {\n    let mut input = String::new();\n    std::io::stdin().read_to_string(&mut input).unwrap();\n    let data = __parse_json(&input);\n    let n = data.get("n").as_int();\n\n    let fb = std::sync::Arc::new(FooBar::new(n));\n    let output: std::sync::Arc<std::sync::Mutex<Vec<String>>> = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));\n\n    let f2 = std::sync::Arc::clone(&fb); let o2 = std::sync::Arc::clone(&output);\n    let t2 = std::thread::spawn(move || { f2.bar(|| { o2.lock().unwrap().push("bar".to_string()); }); });\n    let f1 = std::sync::Arc::clone(&fb); let o1 = std::sync::Arc::clone(&output);\n    let t1 = std::thread::spawn(move || { f1.foo(|| { o1.lock().unwrap().push("foo".to_string()); }); });\n\n    t2.join().unwrap(); t1.join().unwrap();\n\n    let joined: String = output.lock().unwrap().join("");\n    println!("\\"{}\\"", joined);\n}`;
        cd.typescript = `const chunks: any[] = [];\nprocess.stdin.on('data', (chunk: any) => chunks.push(chunk));\nprocess.stdin.on('end', () => {\n    const data = JSON.parse(chunks.join(''));\n    const n: number = data.n;\n    const output: string[] = [];\n    const fb = new FooBar(n);\n    const p1 = new Promise<void>(r => setTimeout(() => { Promise.resolve(fb.bar(() => { output.push('bar'); })).then(() => r()); }, 0));\n    const p2 = new Promise<void>(r => setTimeout(() => { Promise.resolve(fb.foo(() => { output.push('foo'); })).then(() => r()); }, 0));\n    Promise.all([p1, p2]).then(() => console.log(JSON.stringify(output.join(''))));\n});`;
        p!.customDriver = cd;
        await p!.save();
        console.log('Saved: Print FooBar Alternately');
    }

    // ============== Print Zero Even Odd ==============
    {
        const p = await Problem.findOne({ title: 'Print Zero Even Odd' });
        const starterCode: any = p!.starterCode.toObject ? p!.starterCode.toObject() : p!.starterCode;
        starterCode.go = `type ZeroEvenOdd struct {\n\tn int\n}\n\nfunc NewZeroEvenOdd(n int) *ZeroEvenOdd {\n\treturn &ZeroEvenOdd{n: n}\n}\n\nfunc (z *ZeroEvenOdd) Zero(printNumber func(int)) {\n\tfor i := 0; i < z.n; i++ {\n\t\t// Write your solution here\n\t\tprintNumber(0)\n\t}\n}\n\nfunc (z *ZeroEvenOdd) Even(printNumber func(int)) {\n\tfor i := 2; i <= z.n; i += 2 {\n\t\t// Write your solution here\n\t\tprintNumber(i)\n\t}\n}\n\nfunc (z *ZeroEvenOdd) Odd(printNumber func(int)) {\n\tfor i := 1; i <= z.n; i += 2 {\n\t\t// Write your solution here\n\t\tprintNumber(i)\n\t}\n}`;
        starterCode.csharp = `class ZeroEvenOdd {\n    private int n;\n\n    public ZeroEvenOdd(int n) {\n        this.n = n;\n    }\n\n    public void Zero(Action<int> printNumber) {\n        for (int i = 0; i < n; i++) {\n            // Write your solution here\n            printNumber(0);\n        }\n    }\n\n    public void Even(Action<int> printNumber) {\n        for (int i = 2; i <= n; i += 2) {\n            // Write your solution here\n            printNumber(i);\n        }\n    }\n\n    public void Odd(Action<int> printNumber) {\n        for (int i = 1; i <= n; i += 2) {\n            // Write your solution here\n            printNumber(i);\n        }\n    }\n}`;
        starterCode.rust = `pub struct ZeroEvenOdd {\n    n: i32,\n}\n\nimpl ZeroEvenOdd {\n    pub fn new(n: i32) -> Self {\n        ZeroEvenOdd { n }\n    }\n\n    pub fn zero<F: Fn(i32)>(&self, print_number: F) {\n        for _ in 0..self.n {\n            // Write your solution here\n            print_number(0);\n        }\n    }\n\n    pub fn even<F: Fn(i32)>(&self, print_number: F) {\n        let mut i = 2;\n        while i <= self.n {\n            // Write your solution here\n            print_number(i);\n            i += 2;\n        }\n    }\n\n    pub fn odd<F: Fn(i32)>(&self, print_number: F) {\n        let mut i = 1;\n        while i <= self.n {\n            // Write your solution here\n            print_number(i);\n            i += 2;\n        }\n    }\n}`;
        starterCode.typescript = `class ZeroEvenOdd {\n    n: number;\n    constructor(n: number) {\n        this.n = n;\n    }\n\n    zero(printNumber: (x: number) => void): void {\n        for (let i = 0; i < this.n; i++) {\n            // Write your solution here\n            printNumber(0);\n        }\n    }\n\n    even(printNumber: (x: number) => void): void {\n        for (let i = 2; i <= this.n; i += 2) {\n            // Write your solution here\n            printNumber(i);\n        }\n    }\n\n    odd(printNumber: (x: number) => void): void {\n        for (let i = 1; i <= this.n; i += 2) {\n            // Write your solution here\n            printNumber(i);\n        }\n    }\n}`;
        p!.starterCode = starterCode;

        const cd: any = p!.customDriver.toObject ? p!.customDriver.toObject() : p!.customDriver;
        cd.go = `package main\n\nimport (\n\t"encoding/json"\n\t"fmt"\n\t"io"\n\t"os"\n\t"sync"\n)\n\nvar __output []int\nvar __mu sync.Mutex\n\n{{SOLUTION}}\n\nfunc main() {\n\tinputBytes, _ := io.ReadAll(os.Stdin)\n\tvar raw map[string]interface{}\n\tjson.Unmarshal(inputBytes, &raw)\n\tn := int(raw["n"].(float64))\n\n\tzeo := NewZeroEvenOdd(n)\n\tprintNumber := func(x int) { __mu.Lock(); __output = append(__output, x); __mu.Unlock() }\n\tvar wg sync.WaitGroup\n\twg.Add(3)\n\tgo func() { defer wg.Done(); zeo.Even(printNumber) }()\n\tgo func() { defer wg.Done(); zeo.Odd(printNumber) }()\n\tgo func() { defer wg.Done(); zeo.Zero(printNumber) }()\n\twg.Wait()\n\n\tout, _ := json.Marshal(__output)\n\tfmt.Println(string(out))\n}`;
        cd.csharp = `using System;\nusing System.Threading;\nusing System.Collections.Generic;\n${CSHARP_JSON_HELPERS}\n{{SOLUTION}}\n\nclass Program {\n    static List<int> __output = new List<int>();\n    static object __lock = new object();\n\n    static void Main() {\n        string input = Console.In.ReadToEnd();\n        var data = (Dictionary<string, object>)Json.Parse(input);\n        int n = Convert.ToInt32(data["n"]);\n\n        var zeo = new ZeroEvenOdd(n);\n        Action<int> printNumber = x => { lock(__lock) { __output.Add(x); } };\n        var t1 = new Thread(() => zeo.Even(printNumber));\n        var t2 = new Thread(() => zeo.Odd(printNumber));\n        var t3 = new Thread(() => zeo.Zero(printNumber));\n        t1.Start(); t2.Start(); t3.Start();\n        t3.Join(); t1.Join(); t2.Join();\n\n        Console.WriteLine(Json.Stringify(__output));\n    }\n}`;
        cd.rust = `${RUST_JSON_HELPERS}\nuse std::io::Read;\n\nfn main() {\n    let mut input = String::new();\n    std::io::stdin().read_to_string(&mut input).unwrap();\n    let data = __parse_json(&input);\n    let n = data.get("n").as_int();\n\n    let zeo = std::sync::Arc::new(ZeroEvenOdd::new(n));\n    let output: std::sync::Arc<std::sync::Mutex<Vec<i32>>> = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));\n\n    let z1 = std::sync::Arc::clone(&zeo); let o1 = std::sync::Arc::clone(&output);\n    let t1 = std::thread::spawn(move || { z1.even(move |x| { o1.lock().unwrap().push(x); }); });\n    let z2 = std::sync::Arc::clone(&zeo); let o2 = std::sync::Arc::clone(&output);\n    let t2 = std::thread::spawn(move || { z2.odd(move |x| { o2.lock().unwrap().push(x); }); });\n    let z3 = std::sync::Arc::clone(&zeo); let o3 = std::sync::Arc::clone(&output);\n    let t3 = std::thread::spawn(move || { z3.zero(move |x| { o3.lock().unwrap().push(x); }); });\n\n    t1.join().unwrap(); t2.join().unwrap(); t3.join().unwrap();\n\n    let result = output.lock().unwrap().clone();\n    println!("{}", __stringify_int_vec(&result));\n}`;
        cd.typescript = `const chunks: any[] = [];\nprocess.stdin.on('data', (chunk: any) => chunks.push(chunk));\nprocess.stdin.on('end', () => {\n    const data = JSON.parse(chunks.join(''));\n    const n: number = data.n;\n    const output: number[] = [];\n    const zeo = new ZeroEvenOdd(n);\n    const printNumber = (x: number) => { output.push(x); };\n    const p1 = new Promise<void>(r => setTimeout(() => { Promise.resolve(zeo.even(printNumber)).then(() => r()); }, 0));\n    const p2 = new Promise<void>(r => setTimeout(() => { Promise.resolve(zeo.odd(printNumber)).then(() => r()); }, 0));\n    const p3 = new Promise<void>(r => setTimeout(() => { Promise.resolve(zeo.zero(printNumber)).then(() => r()); }, 0));\n    Promise.all([p1, p2, p3]).then(() => console.log(JSON.stringify(output)));\n});`;
        p!.customDriver = cd;
        await p!.save();
        console.log('Saved: Print Zero Even Odd');
    }

    // ============== Fizz Buzz Multithreaded ==============
    {
        const p = await Problem.findOne({ title: 'Fizz Buzz Multithreaded' });
        const starterCode: any = p!.starterCode.toObject ? p!.starterCode.toObject() : p!.starterCode;
        starterCode.go = `type FizzBuzz struct {\n\tn int\n}\n\nfunc NewFizzBuzz(n int) *FizzBuzz {\n\treturn &FizzBuzz{n: n}\n}\n\nfunc (f *FizzBuzz) Fizz(printFizz func()) {\n\t// printFizz() outputs "fizz". Do not change or remove this line.\n\t// Write your solution here\n}\n\nfunc (f *FizzBuzz) Buzz(printBuzz func()) {\n\t// printBuzz() outputs "buzz". Do not change or remove this line.\n\t// Write your solution here\n}\n\nfunc (f *FizzBuzz) Fizzbuzz(printFizzBuzz func()) {\n\t// printFizzBuzz() outputs "fizzbuzz". Do not change or remove this line.\n\t// Write your solution here\n}\n\nfunc (f *FizzBuzz) Number(printNumber func(int)) {\n\t// printNumber(x) outputs x. Do not change or remove this line.\n\t// Write your solution here\n}`;
        starterCode.csharp = `class FizzBuzz {\n    private int n;\n\n    public FizzBuzz(int n) {\n        this.n = n;\n    }\n\n    public void Fizz(Action printFizz) {\n        // printFizz() outputs "fizz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    public void Buzz(Action printBuzz) {\n        // printBuzz() outputs "buzz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    public void Fizzbuzz(Action printFizzBuzz) {\n        // printFizzBuzz() outputs "fizzbuzz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    public void Number(Action<int> printNumber) {\n        // printNumber(x) outputs x. Do not change or remove this line.\n        // Write your solution here\n    }\n}`;
        starterCode.rust = `pub struct FizzBuzz {\n    n: i32,\n}\n\nimpl FizzBuzz {\n    pub fn new(n: i32) -> Self {\n        FizzBuzz { n }\n    }\n\n    pub fn fizz<F: Fn()>(&self, print_fizz: F) {\n        // print_fizz() outputs "fizz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    pub fn buzz<F: Fn()>(&self, print_buzz: F) {\n        // print_buzz() outputs "buzz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    pub fn fizzbuzz<F: Fn()>(&self, print_fizzbuzz: F) {\n        // print_fizzbuzz() outputs "fizzbuzz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    pub fn number<F: Fn(i32)>(&self, print_number: F) {\n        // print_number(x) outputs x. Do not change or remove this line.\n        // Write your solution here\n    }\n}`;
        starterCode.typescript = `class FizzBuzz {\n    n: number;\n    constructor(n: number) {\n        this.n = n;\n    }\n\n    fizz(printFizz: () => void): void {\n        // printFizz() outputs "fizz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    buzz(printBuzz: () => void): void {\n        // printBuzz() outputs "buzz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    fizzbuzz(printFizzBuzz: () => void): void {\n        // printFizzBuzz() outputs "fizzbuzz". Do not change or remove this line.\n        // Write your solution here\n    }\n\n    number(printNumber: (x: number) => void): void {\n        // printNumber(x) outputs x. Do not change or remove this line.\n        // Write your solution here\n    }\n}`;
        p!.starterCode = starterCode;

        const cd: any = p!.customDriver.toObject ? p!.customDriver.toObject() : p!.customDriver;
        cd.go = `package main\n\nimport (\n\t"encoding/json"\n\t"fmt"\n\t"io"\n\t"os"\n\t"sync"\n)\n\nvar __output []string\nvar __mu sync.Mutex\n\n{{SOLUTION}}\n\nfunc main() {\n\tinputBytes, _ := io.ReadAll(os.Stdin)\n\tvar raw map[string]interface{}\n\tjson.Unmarshal(inputBytes, &raw)\n\tn := int(raw["n"].(float64))\n\n\tfb := NewFizzBuzz(n)\n\tvar wg sync.WaitGroup\n\twg.Add(4)\n\tgo func() { defer wg.Done(); fb.Buzz(func() { __mu.Lock(); __output = append(__output, "buzz"); __mu.Unlock() }) }()\n\tgo func() { defer wg.Done(); fb.Fizzbuzz(func() { __mu.Lock(); __output = append(__output, "fizzbuzz"); __mu.Unlock() }) }()\n\tgo func() { defer wg.Done(); fb.Number(func(x int) { __mu.Lock(); __output = append(__output, fmt.Sprintf("%d", x)); __mu.Unlock() }) }()\n\tgo func() { defer wg.Done(); fb.Fizz(func() { __mu.Lock(); __output = append(__output, "fizz"); __mu.Unlock() }) }()\n\twg.Wait()\n\n\tout, _ := json.Marshal(__output)\n\tfmt.Println(string(out))\n}`;
        cd.csharp = `using System;\nusing System.Threading;\nusing System.Collections.Generic;\n${CSHARP_JSON_HELPERS}\n{{SOLUTION}}\n\nclass Program {\n    static List<string> __output = new List<string>();\n    static object __lock = new object();\n\n    static void Main() {\n        string input = Console.In.ReadToEnd();\n        var data = (Dictionary<string, object>)Json.Parse(input);\n        int n = Convert.ToInt32(data["n"]);\n\n        var fb = new FizzBuzz(n);\n        var t2 = new Thread(() => fb.Buzz(() => { lock(__lock) { __output.Add("buzz"); } }));\n        var t3 = new Thread(() => fb.Fizzbuzz(() => { lock(__lock) { __output.Add("fizzbuzz"); } }));\n        var t4 = new Thread(() => fb.Number(x => { lock(__lock) { __output.Add(x.ToString()); } }));\n        var t1 = new Thread(() => fb.Fizz(() => { lock(__lock) { __output.Add("fizz"); } }));\n        t2.Start(); t3.Start(); t4.Start(); t1.Start();\n        t1.Join(); t2.Join(); t3.Join(); t4.Join();\n\n        Console.WriteLine(Json.Stringify(__output));\n    }\n}`;
        cd.rust = `${RUST_JSON_HELPERS}\nuse std::io::Read;\n\nfn main() {\n    let mut input = String::new();\n    std::io::stdin().read_to_string(&mut input).unwrap();\n    let data = __parse_json(&input);\n    let n = data.get("n").as_int();\n\n    let fb = std::sync::Arc::new(FizzBuzz::new(n));\n    let output: std::sync::Arc<std::sync::Mutex<Vec<String>>> = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));\n\n    let f2 = std::sync::Arc::clone(&fb); let o2 = std::sync::Arc::clone(&output);\n    let t2 = std::thread::spawn(move || { f2.buzz(|| { o2.lock().unwrap().push("buzz".to_string()); }); });\n    let f3 = std::sync::Arc::clone(&fb); let o3 = std::sync::Arc::clone(&output);\n    let t3 = std::thread::spawn(move || { f3.fizzbuzz(|| { o3.lock().unwrap().push("fizzbuzz".to_string()); }); });\n    let f4 = std::sync::Arc::clone(&fb); let o4 = std::sync::Arc::clone(&output);\n    let t4 = std::thread::spawn(move || { f4.number(move |x| { o4.lock().unwrap().push(x.to_string()); }); });\n    let f1 = std::sync::Arc::clone(&fb); let o1 = std::sync::Arc::clone(&output);\n    let t1 = std::thread::spawn(move || { f1.fizz(|| { o1.lock().unwrap().push("fizz".to_string()); }); });\n\n    t1.join().unwrap(); t2.join().unwrap(); t3.join().unwrap(); t4.join().unwrap();\n\n    let joined = output.lock().unwrap().clone();\n    println!("{}", __stringify_str_vec(&joined));\n}`;
        cd.typescript = `const chunks: any[] = [];\nprocess.stdin.on('data', (chunk: any) => chunks.push(chunk));\nprocess.stdin.on('end', () => {\n    const data = JSON.parse(chunks.join(''));\n    const n: number = data.n;\n    const output: string[] = [];\n    const fb = new FizzBuzz(n);\n    const p1 = new Promise<void>(r => setTimeout(() => { Promise.resolve(fb.buzz(() => { output.push('buzz'); })).then(() => r()); }, 0));\n    const p2 = new Promise<void>(r => setTimeout(() => { Promise.resolve(fb.fizzbuzz(() => { output.push('fizzbuzz'); })).then(() => r()); }, 0));\n    const p3 = new Promise<void>(r => setTimeout(() => { Promise.resolve(fb.number((x: number) => { output.push(String(x)); })).then(() => r()); }, 0));\n    const p4 = new Promise<void>(r => setTimeout(() => { Promise.resolve(fb.fizz(() => { output.push('fizz'); })).then(() => r()); }, 0));\n    Promise.all([p1, p2, p3, p4]).then(() => console.log(JSON.stringify(output)));\n});`;
        p!.customDriver = cd;
        await p!.save();
        console.log('Saved: Fizz Buzz Multithreaded');
    }

    await mongoose.disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
